### ISSUE TITLE
Shifts : available suggestions not working

### ISSUE THREAD

**Issue by snowstorm257** [uOttawa-Makerspace/MakerRepoApp#12]
When I create a shift some users are marked always as ''unavailable''. Seems to only affect some users such as Adrien Ambroise. 

Unknown reason as of yet

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVBNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b1f50a8d6597c1fe8bb51748c28ae298383c4b8e/MicrosoftTeams-image%20%281%29.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWJNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ca3638836e22232c0f5f87c878678e6abb26d517/MicrosoftTeams-image.png)

**Comment by Columbium41** [comment]
fixed last semester
