### ISSUE TITLE
Admin area shifts dropdown alphabetize

### ISSUE THREAD

**Issue by snowstorm257** [uOttawa-Makerspace/MakerRepoApp#28]
When we create a shift in the admin area make all dropdowns alphabetical order. dont mix available and unavailable 

<img width="512" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2pEQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bf1ac997dc24aa0b67861ba6f108474c0f9ed2b0/image.png" alt="image.png" />

**Comment by Columbium41** [comment]
user dropdown should already be in alphabetical order. time period should be sorted by date

**Comment by ChristopherLit** [comment]
Fixed
